import * as React from 'react';
import { DetailsList, IColumn, SelectionMode, CheckboxVisibility, DetailsListLayoutMode } from '@fluentui/react/lib/DetailsList';
import { Stack } from '@fluentui/react/lib/Stack';
import { Text } from '@fluentui/react/lib/Text';
import { IconButton } from '@fluentui/react/lib/Button';
import { Pivot, PivotItem } from '@fluentui/react/lib/Pivot';
import { Dropdown } from '@fluentui/react/lib/Dropdown';
import { Toggle } from '@fluentui/react/lib/Toggle';
import { Link } from '@fluentui/react/lib/Link';
import { Icon } from '@fluentui/react/lib/Icon';
import { useTheme, ITheme } from '@fluentui/react';
import { mergeStyleSets } from '@fluentui/merge-styles';
import { memoizeFunction } from '@fluentui/utilities';
import { IGeneratedDocument, ISupportingDocument } from '../../types/models';

const getClassNames = memoizeFunction((theme: ITheme) =>
  mergeStyleSets({
    root: { padding: '16px 24px', flex: 1 },
    banner: {
      backgroundColor: '#DEECF9',
      borderRadius: 4,
      padding: '16px 20px',
      display: 'flex',
      alignItems: 'center',
      gap: 16,
    },
    bannerIcon: {
      fontSize: 40,
      color: theme.palette.themePrimary,
    },
    sectionHeader: {
      backgroundColor: theme.palette.neutralLighterAlt,
      padding: '10px 16px',
      fontWeight: 600,
      fontSize: 14,
      cursor: 'pointer',
    },
    downloadBtn: {
      color: theme.palette.neutralSecondary,
    },
  })
);

export interface IDocumentsPageProps {
  generatedDocuments: IGeneratedDocument[];
  supportingDocuments: ISupportingDocument[];
  onGoToProposal: () => void;
}

export const DocumentsPage: React.FC<IDocumentsPageProps> = ({
  generatedDocuments,
  supportingDocuments,
  onGoToProposal,
}) => {
  const theme = useTheme();
  const classNames = getClassNames(theme);
  const [genExpanded, setGenExpanded] = React.useState(true);
  const [supExpanded, setSupExpanded] = React.useState(true);
  const [uploadExpanded, setUploadExpanded] = React.useState(true);

  const genColumns: IColumn[] = React.useMemo(
    () => [
      {
        key: 'file',
        name: 'File',
        minWidth: 350,
        isResizable: true,
        isSorted: true,
        isSortedDescending: false,
        onRender: (item: IGeneratedDocument) => (
          <Stack horizontal verticalAlign="center" tokens={{ childrenGap: 8 }}>
            <Icon iconName="PDF" styles={{ root: { color: '#D13438', fontSize: 16 } }} />
            <Text styles={{ root: { fontSize: 13 } }}>{item.fileName}</Text>
          </Stack>
        ),
      },
      { key: 'type', name: 'Type', fieldName: 'type', minWidth: 60, maxWidth: 80, isSorted: true },
      { key: 'language', name: 'Language', fieldName: 'language', minWidth: 80, maxWidth: 100, isSorted: true },
      { key: 'generatedBy', name: 'Generated by', fieldName: 'generatedBy', minWidth: 120, maxWidth: 160, isSorted: true },
      { key: 'generatedOn', name: 'Generated On', fieldName: 'generatedOn', minWidth: 140, maxWidth: 180, isSorted: true },
      {
        key: 'actions',
        name: 'Actions',
        minWidth: 40,
        maxWidth: 40,
        onRender: () => (
          <IconButton iconProps={{ iconName: 'Download' }} ariaLabel="Download" className={classNames.downloadBtn} />
        ),
      },
    ],
    [classNames]
  );

  const supColumns: IColumn[] = React.useMemo(
    () => [
      {
        key: 'file',
        name: 'File',
        minWidth: 350,
        isResizable: true,
        isSorted: true,
        onRender: (item: ISupportingDocument) => (
          <Stack horizontal verticalAlign="center" tokens={{ childrenGap: 8 }}>
            <Icon iconName="ExcelDocument" styles={{ root: { color: '#107C10', fontSize: 16 } }} />
            <Text styles={{ root: { fontSize: 13 } }}>{item.fileName}</Text>
          </Stack>
        ),
      },
      { key: 'uploadedBy', name: 'Uploaded by', fieldName: 'uploadedBy', minWidth: 120, maxWidth: 160, isSorted: true },
      { key: 'uploadedOn', name: 'Uploaded On', fieldName: 'uploadedOn', minWidth: 140, maxWidth: 180, isSorted: true },
      {
        key: 'actions',
        name: 'Actions',
        minWidth: 40,
        maxWidth: 40,
        onRender: () => (
          <IconButton iconProps={{ iconName: 'Download' }} ariaLabel="Download" className={classNames.downloadBtn} />
        ),
      },
    ],
    [classNames]
  );

  return (
    <Stack className={classNames.root} tokens={{ childrenGap: 16 }}>
      {/* CPS / Amendments tabs */}
      <Pivot>
        <PivotItem headerText="CPS" />
        <PivotItem headerText="Amendments" />
      </Pivot>

      {/* Version dropdown */}
      <Dropdown
        selectedKey="latest"
        options={[{ key: 'latest', text: '1103281.003 (latest)' }]}
        styles={{ dropdown: { width: 200 } }}
      />

      {/* Blue banner */}
      <div className={classNames.banner}>
        <Icon iconName="AirplaneSolid" className={classNames.bannerIcon} />
        <Stack tokens={{ childrenGap: 2 }}>
          <Text styles={{ root: { fontSize: 14 } }}>
            Your proposal is pending approval. <Link onClick={onGoToProposal}>Go to proposal</Link>
          </Text>
          <Text styles={{ root: { fontSize: 12, color: theme.palette.neutralSecondary } }}>
            Tip: For a quicker approval, add notes and supporting documentation.
          </Text>
        </Stack>
      </div>

      {/* Generated documents */}
      <Stack
        horizontal
        verticalAlign="center"
        horizontalAlign="space-between"
        className={classNames.sectionHeader}
        onClick={() => setGenExpanded(!genExpanded)}
      >
        <Text styles={{ root: { fontWeight: 600 } }}>Generated documents ({generatedDocuments.length})</Text>
        <Icon iconName={genExpanded ? 'ChevronDown' : 'ChevronRight'} />
      </Stack>

      {genExpanded && (
        <Stack tokens={{ childrenGap: 4 }}>
          <Stack horizontal verticalAlign="center" horizontalAlign="space-between">
            <Stack horizontal verticalAlign="center" tokens={{ childrenGap: 4 }}>
              <Icon iconName="Download" styles={{ root: { color: theme.palette.neutralTertiary } }} />
              <Text styles={{ root: { fontSize: 13, color: theme.palette.neutralTertiary } }}>Download</Text>
            </Stack>
            <Toggle label="Show Excel Documents" inlineLabel styles={{ root: { marginBottom: 0 } }} />
          </Stack>
          <DetailsList
            items={generatedDocuments}
            columns={genColumns}
            selectionMode={SelectionMode.multiple}
            checkboxVisibility={CheckboxVisibility.always}
            layoutMode={DetailsListLayoutMode.justified}
            getKey={(item) => (item as IGeneratedDocument).id}
            compact
          />
        </Stack>
      )}

      {/* Uploaded documents */}
      <Stack
        horizontal
        verticalAlign="center"
        horizontalAlign="space-between"
        className={classNames.sectionHeader}
        onClick={() => setUploadExpanded(!uploadExpanded)}
      >
        <Text styles={{ root: { fontWeight: 600 } }}>Uploaded documents (0)</Text>
        <Icon iconName={uploadExpanded ? 'ChevronRight' : 'ChevronRight'} />
      </Stack>

      {/* Supporting documents */}
      <Stack
        horizontal
        verticalAlign="center"
        horizontalAlign="space-between"
        className={classNames.sectionHeader}
        onClick={() => setSupExpanded(!supExpanded)}
      >
        <Stack horizontal verticalAlign="center" tokens={{ childrenGap: 4 }}>
          <Text styles={{ root: { fontWeight: 600 } }}>Supporting documents ({supportingDocuments.length})</Text>
          <Icon iconName="Info" styles={{ root: { fontSize: 12, color: theme.palette.neutralSecondary } }} />
        </Stack>
        <Icon iconName={supExpanded ? 'ChevronDown' : 'ChevronRight'} />
      </Stack>

      {supExpanded && (
        <Stack tokens={{ childrenGap: 4 }}>
          <Stack horizontal verticalAlign="center" tokens={{ childrenGap: 4 }}>
            <Icon iconName="Download" styles={{ root: { color: theme.palette.neutralTertiary } }} />
            <Text styles={{ root: { fontSize: 13, color: theme.palette.neutralTertiary } }}>Download</Text>
          </Stack>
          <DetailsList
            items={supportingDocuments}
            columns={supColumns}
            selectionMode={SelectionMode.multiple}
            checkboxVisibility={CheckboxVisibility.always}
            layoutMode={DetailsListLayoutMode.justified}
            getKey={(item) => (item as ISupportingDocument).id}
            compact
          />
        </Stack>
      )}
    </Stack>
  );
};
